/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Clear Workspace */
        delete: operations["clear_workspace_api_v1_workspace_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_v1_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/check-gemini": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check Gemini */
        post: operations["check_gemini_api_v1_settings_check_gemini_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Demo Profile */
        post: operations["demo_profile_api_v1_profile_demo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parse Profile */
        post: operations["parse_profile_api_v1_profile_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Job */
        post: operations["import_job_api_v1_jobs_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Discover */
        post: operations["discover_api_v1_jobs_discover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_v1_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/requirements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Requirements */
        get: operations["get_requirements_api_v1_jobs__job_id__requirements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Job */
        post: operations["analyze_job_api_v1_jobs__job_id__analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Match */
        post: operations["create_match_api_v1_matches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/tailor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tailor */
        post: operations["tailor_api_v1_resumes_tailor_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/export/{format}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Resume */
        post: operations["export_resume_api_v1_resumes_export__format__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Applications */
        get: operations["list_applications_api_v1_applications_get"];
        put?: never;
        /** Create Application */
        post: operations["create_application_api_v1_applications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Application */
        patch: operations["update_application_api_v1_applications__application_id__patch"];
        trace?: never;
    };
    "/api/v1/insights/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Skills */
        get: operations["skills_api_v1_insights_skills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApplicationRecord */
        ApplicationRecord: {
            /** Id */
            id: string;
            /** Job Id */
            job_id: string;
            /** @default DISCOVERED */
            status: components["schemas"]["ApplicationStatus"];
            /** Official Url */
            official_url?: string | null;
            /**
             * Notes
             * @default
             */
            notes: string;
            /** Resume Version Id */
            resume_version_id?: string | null;
        };
        /**
         * ApplicationStatus
         * @enum {string}
         */
        ApplicationStatus: "DISCOVERED" | "SHORTLISTED" | "RESUME_READY" | "READY_TO_APPLY" | "APPLIED" | "RECRUITER_RESPONSE" | "INTERVIEW" | "OFFER" | "REJECTED" | "WITHDRAWN";
        /** Body_parse_profile_api_v1_profile_parse_post */
        Body_parse_profile_api_v1_profile_parse_post: {
            /** File */
            file: string;
        };
        /** CandidateFact */
        CandidateFact: {
            /** Id */
            id: string;
            /** Category */
            category: string;
            /** Subject */
            subject: string;
            /** Predicate */
            predicate: string;
            /** Value */
            value: string;
            /** Source Section */
            source_section?: string | null;
            /** Source Text */
            source_text?: string | null;
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
            /**
             * Verified By User
             * @default false
             */
            verified_by_user: boolean;
            /**
             * Immutable
             * @default true
             */
            immutable: boolean;
        };
        /** CandidateProfile */
        CandidateProfile: {
            /** Name */
            name: string;
            /**
             * Summary
             * @default
             */
            summary: string;
            /**
             * Skills
             * @default []
             */
            skills: string[];
            /**
             * Experience Years
             * @default 0
             */
            experience_years: number;
            /**
             * Locations
             * @default []
             */
            locations: string[];
            /**
             * Facts
             * @default []
             */
            facts: components["schemas"]["CandidateFact"][];
        };
        /** EvidenceMatch */
        EvidenceMatch: {
            /** Requirement */
            requirement: string;
            /**
             * Candidate Fact Ids
             * @default []
             */
            candidate_fact_ids: string[];
            /**
             * Evidence
             * @default []
             */
            evidence: string[];
            /** Alignment */
            alignment: string;
            /** Confidence */
            confidence: number;
        };
        /** ExportRequest */
        ExportRequest: {
            candidate: components["schemas"]["CandidateProfile"];
            version: components["schemas"]["ResumeVersion"];
        };
        /** GeneratedResumeBullet */
        GeneratedResumeBullet: {
            /** Text */
            text: string;
            /** Source Fact Ids */
            source_fact_ids: string[];
            /**
             * Transformation Type
             * @default rephrase
             */
            transformation_type: string;
            /** @default PENDING */
            verification_status: components["schemas"]["VerificationStatus"];
            /**
             * Verifier Notes
             * @default []
             */
            verifier_notes: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportJob */
        ImportJob: {
            /** Title */
            title: string;
            /** Company */
            company: string;
            /** Description */
            description: string;
            /** Location */
            location?: string | null;
        };
        /** JobRecord */
        JobRecord: {
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** External Job Id */
            external_job_id?: string | null;
            /** Title */
            title: string;
            /** Company */
            company: string;
            /** Location */
            location?: string | null;
            /** Work Mode */
            work_mode?: string | null;
            /** Description */
            description: string;
            /** Canonical Url */
            canonical_url?: string | null;
            /** Posted At */
            posted_at?: string | null;
            /** Discovered At */
            discovered_at?: string | null;
            /** Last Verified At */
            last_verified_at?: string | null;
            /** @default UNKNOWN */
            status: components["schemas"]["JobStatus"];
            /** Verification Evidence */
            verification_evidence?: string | null;
        };
        /** JobRequirement */
        JobRequirement: {
            /** Role Title */
            role_title: string;
            /** Role Family */
            role_family?: string | null;
            /**
             * Mandatory Skills
             * @default []
             */
            mandatory_skills: string[];
            /**
             * Preferred Skills
             * @default []
             */
            preferred_skills: string[];
            /**
             * Responsibilities
             * @default []
             */
            responsibilities: string[];
            /**
             * Education Requirements
             * @default []
             */
            education_requirements: string[];
            /** Minimum Experience */
            minimum_experience?: number | null;
            /** Maximum Experience */
            maximum_experience?: number | null;
            /** Location */
            location?: string | null;
            /** Work Mode */
            work_mode?: string | null;
            /** Employment Type */
            employment_type?: string | null;
            /** Domain */
            domain?: string | null;
            /** Seniority */
            seniority?: string | null;
            /**
             * Certifications
             * @default []
             */
            certifications: string[];
            /**
             * Keywords
             * @default []
             */
            keywords: string[];
            /** Salary */
            salary?: string | null;
            /**
             * Ambiguities
             * @default []
             */
            ambiguities: string[];
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "OPEN" | "CLOSED" | "UNKNOWN" | "STALE" | "ERROR";
        /** MatchRequest */
        MatchRequest: {
            candidate: components["schemas"]["CandidateProfile"];
            job: components["schemas"]["JobRecord"];
            requirement: components["schemas"]["JobRequirement"];
        };
        /** MatchResult */
        MatchResult: {
            /** Eligible */
            eligible: boolean;
            /**
             * Eligibility Warnings
             * @default []
             */
            eligibility_warnings: string[];
            score: components["schemas"]["ScoreBreakdown"];
            /**
             * Evidence
             * @default []
             */
            evidence: components["schemas"]["EvidenceMatch"][];
            /**
             * Gaps
             * @default []
             */
            gaps: {
                [key: string]: string;
            }[];
        };
        /** ResumeVersion */
        ResumeVersion: {
            /** Id */
            id: string;
            /** Target Job Id */
            target_job_id?: string | null;
            /** Company */
            company?: string | null;
            /**
             * Bullets
             * @default []
             */
            bullets: components["schemas"]["GeneratedResumeBullet"][];
            /** @default PENDING */
            verification_status: components["schemas"]["VerificationStatus"];
        };
        /** ScoreBreakdown */
        ScoreBreakdown: {
            /**
             * Required Skill Coverage
             * @default 0
             */
            required_skill_coverage: number;
            /**
             * Relevant Evidence
             * @default 0
             */
            relevant_evidence: number;
            /**
             * Semantic Role Alignment
             * @default 0
             */
            semantic_role_alignment: number;
            /**
             * Responsibility Alignment
             * @default 0
             */
            responsibility_alignment: number;
            /**
             * Experience Alignment
             * @default 0
             */
            experience_alignment: number;
            /**
             * Preferred Skill Coverage
             * @default 0
             */
            preferred_skill_coverage: number;
            /**
             * Location Work Mode
             * @default 0
             */
            location_work_mode: number;
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /** TailorRequest */
        TailorRequest: {
            candidate: components["schemas"]["CandidateProfile"];
            requirement: components["schemas"]["JobRequirement"];
            /** Job Id */
            job_id?: string | null;
            /** Company */
            company?: string | null;
            /**
             * Consent
             * @default false
             */
            consent: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VerificationStatus
         * @enum {string}
         */
        VerificationStatus: "PENDING" | "PASSED" | "FAILED";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    clear_workspace_api_v1_workspace_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    status_api_v1_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    check_gemini_api_v1_settings_check_gemini_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    demo_profile_api_v1_profile_demo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateProfile"];
                };
            };
        };
    };
    parse_profile_api_v1_profile_parse_post: {
        parameters: {
            query?: {
                consent?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_parse_profile_api_v1_profile_parse_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_job_api_v1_jobs_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportJob"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discover_api_v1_jobs_discover_post: {
        parameters: {
            query?: {
                query?: string;
                source?: string;
                board?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_v1_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecord"][];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_requirements_api_v1_jobs__job_id__requirements_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRequirement"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_job_api_v1_jobs__job_id__analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRequirement"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_match_api_v1_matches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tailor_api_v1_resumes_tailor_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TailorRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeVersion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_resume_api_v1_resumes_export__format__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                format: "pdf" | "docx";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_applications_api_v1_applications_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationRecord"][];
                };
            };
        };
    };
    create_application_api_v1_applications_post: {
        parameters: {
            query: {
                job_id: string;
                official_url?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_application_api_v1_applications__application_id__patch: {
        parameters: {
            query: {
                status: components["schemas"]["ApplicationStatus"];
            };
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    skills_api_v1_insights_skills_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
